import Head from 'next/head'
import { Home } from '@/components/Home/Home'
import GameProvider from '@/providers/GameProvider/GameProvider'

export default function Index() {
  return (
    <>
      <Head>
        <title>WORDLE JITSU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GameProvider>
        <Home />
      </GameProvider>
    </>
  )
}
