import Head from 'next/head'
import { Game } from '@/components/Game/Game'
import GameProvider from '@/providers/GameProvider/GameProvider'
import { ThemeProvider } from 'styled-components'
import { theme } from '@/theme'
import { ModalProvider } from 'styled-react-modal'

export default function Index() {
  return (
    <>
      <Head>
        <title>WORDLE JITSU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <ModalProvider>
          <GameProvider>
            <Game />
          </GameProvider>
        </ModalProvider>
      </ThemeProvider>
    </>
  )
}
