# Generated by Django 3.2.13 on 2023-01-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
